In [1]:
import pandas as pd
import numpy as np

In [5]:
pip install --upgrade nbformat plotly

^C
Note: you may need to restart the kernel to use updated packages.

In [2]:
import plotly.express as pltexp

In [3]:
df = pd.read_pickle("df_unite.pkl")

In [4]:
df_date = [i.year for i in df["first_release_date"]]
df_year = pd.DataFrame(df_date, columns=['col_name'])
df_with_year = pd.merge(df, df_year, left_index=True, right_index=True, how='inner')
df_with_year = df_with_year.rename(columns={'col_name': 'year'})

В данном документе рассмотрим более детальную аналитику, которая уже напрямую позволит вывести допущения и бизнес-вывод. Нам, как аналитикам, очень интересно понять, какие вообще игры популярны сейчас. Может быть есть какой-то тренд на рост/падение интереса к определённым жанрам. Тогда, конечно, не стоит создавать такие игры

## График 1: Доля жанров по годам

In [5]:
box_genre = []

for elems in df.columns:
    if "genre" in elems:
        box_genre.append(elems)

In [6]:
df_by_years = df_with_year[df_with_year['year'].between(1995, 2025)]
df_by_years = df_by_years.groupby('year')[box_genre].sum()

In [7]:
df_by_years

,genre_Adventure,genre_Arcade,genre_Card & Board Game,genre_Fighting,genre_Hack and slash/Beat 'em up,genre_Indie,genre_MOBA,genre_Music,genre_Pinball,genre_Platform,...,genre_Racing,genre_Real Time Strategy (RTS),genre_Role-playing (RPG),genre_Shooter,genre_Simulator,genre_Sport,genre_Strategy,genre_Tactical,genre_Turn-based strategy (TBS),genre_Visual Novel
year,,,,,,,,,,,,,,,,,,,,,
1995.0,57,32,2,33,9,2,0,0,4,51,...,15,5,24,43,15,21,24,9,7,1
1996.0,66,38,0,33,8,4,0,1,0,29,...,19,9,36,47,18,26,36,7,15,4
1997.0,63,34,2,27,9,4,0,1,1,40,...,27,20,30,60,35,32,44,7,9,1
1998.0,93,26,5,35,11,9,0,3,1,32,...,40,21,40,55,42,36,48,9,7,0
1999.0,107,24,3,33,15,6,0,5,1,39,...,47,17,62,74,50,36,52,16,16,0
2000.0,86,23,4,23,20,5,0,3,2,40,...,42,21,44,58,51,38,65,13,18,3
2001.0,94,27,6,25,17,9,0,6,0,42,...,45,29,55,54,55,41,74,19,19,0
2002.0,130,23,6,30,19,12,0,5,1,60,...,39,25,69,75,65,73,75,28,18,4
2003.0,130,26,9,41,34,15,0,3,2,47,...,52,30,86,79,75,50,95,32,27,2
2004.0,136,24,7,33,25,19,0,6,2,57,...,33,26,76,99,60,44,64,22,19,5
2005.0,137,23,10,37,43,17,0,9,1,55,...,48,23,84,98,66,46,78,37,21,5
2006.0,163,24,7,46,28,27,0,10,1,45,...,56,40,104,89,101,53,117,23,30,5
2007.0,168,35,10,22,30,41,1,16,0,50,...,37,33,102,97,80,45,103,17,20,7
2008.0,187,30,4,34,27,63,0,23,2,57,...,35,27,110,88,91,51,99,18,19,10
2009.0,223,47,15,33,37,88,1,30,1,65,...,41,46,134,129,89,54,111,15,28,13
2010.0,228,56,9,29,41,105,1,20,1,76,...,39,23,117,115,88,58,96,18,25,13
2011.0,244,62,9,27,49,152,0,24,1,89,...,38,31,121,150,109,58,136,29,19,20
2012.0,335,88,11,39,54,234,1,29,2,105,...,44,37,165,155,124,56,177,28,31,22
2013.0,418,96,23,46,65,331,1,19,1,130,...,46,31,210,172,171,56,200,33,53,30
2014.0,541,128,19,40,47,579,4,27,2,153,...,49,38,276,186,203,61,265,28,67,34
2015.0,765,145,28,45,72,845,5,26,0,159,...,64,40,387,184,279,69,339,48,73,72
2016.0,862,197,45,62,58,1047,3,34,5,162,...,78,52,370,238,382,98,371,36,60,80
2017.0,883,204,41,67,58,1080,2,29,1,164,...,72,40,389,248,405,94,357,39,52,69
2018.0,771,184,36,67,69,888,5,37,3,169,...,74,40,401,188,339,95,315,54,58,63
2019.0,713,142,31,42,49,773,0,25,2,143,...,58,28,360,170,299,70,258,45,68,65
2020.0,464,86,24,34,42,480,3,17,1,97,...,39,19,244,127,217,47,186,33,44,51
2021.0,379,58,23,29,36,349,2,13,0,97,...,22,10,197,94,152,27,122,25,34,37
2022.0,308,66,20,22,35,280,1,13,2,62,...,26,8,140,96,139,38,100,24,22,31
2023.0,326,42,14,25,26,282,2,9,0,77,...,14,10,181,90,120,23,111,40,33,19
2024.0,314,40,11,20,28,291,4,2,0,61,...,13,10,160,75,130,19,98,20,18,20
2025.0,220,28,12,9,23,198,5,5,0,34,...,19,5,112,61,100,18,64,14,19,10

In [8]:
box_by_years = []
for elems in df_by_years.columns:
    box_by_years.append(elems.replace('genre_', ''))

In [9]:
df_by_years.columns = box_by_years

In [10]:
df_by_years = df_by_years.div(df_by_years.sum(axis=1), axis=0)

In [11]:
pltexp.area(df_by_years.reset_index(), x='year', y=df_by_years.columns, title='Доля жанров по годам')

## График 2: Средний рейтинг по годам

Мы построили график, в котором можно посмотреть долю жанров по годам выхода различных игрушек. Теперь давайте в целом посмотрим, а как меняется рейтинг игр от года к году. Это, вместе с анализом рынка/кризисов, поможет нам более детально понимать, в какие периоды стоит выпускать много игр, а когда лучше придержать коней и доработать игру, не выпуская её в невыгодный для рынка момент

In [12]:
df_with_year.info()

<class 'pandas.DataFrame'>
RangeIndex: 23203 entries, 0 to 23202
Data columns (total 93 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   aggregated_rating                                     10274 non-null  float64
 1   aggregated_rating_count                               10274 non-null  float64
 2   first_release_date                                    23182 non-null  object
 3   keywords                                              18391 non-null  object
 4   name                                                  23203 non-null  str
 5   rating                                                23203 non-null  float64
 6   rating_count                                          23203 non-null  int64
 7   slug                                                  23203 non-null  str
 8   total_rating                                          23203 non-null  float64
 9   total_rating_count                                    23203 non-null  int64
 10  game_type                                             23203 non-null  int64
 11  hypes                                                 3935 non-null   float64
 12  remasters                                             697 non-null    object
 13  remakes                                               527 non-null    object
 14  franchise                                             1018 non-null   float64
 15  parent_game                                           2752 non-null   float64
 16  new_companies                                         21917 non-null  str
 17  platform_PC (Microsoft Windows)                       23203 non-null  int64
 18  platform_Mac                                          23203 non-null  int64
 19  platform_Linux                                        23203 non-null  int64
 20  platform_PlayStation                                  23203 non-null  int64
 21  platform_Xbox                                         23203 non-null  int64
 22  platform_Nintendo                                     23203 non-null  int64
 23  platform_Arcade                                       23203 non-null  int64
 24  platform_Wii                                          23203 non-null  int64
 25  platform_Mobile                                       23203 non-null  int64
 26  platform_Other                                        23203 non-null  int64
 27  available_platforms                                   23202 non-null  float64
 28  mode_Battle Royale                                    23203 non-null  int64
 29  mode_Co-operative                                     23203 non-null  int64
 30  mode_Massively Multiplayer Online (MMO)               23203 non-null  int64
 31  mode_Multiplayer                                      23203 non-null  int64
 32  mode_Single player                                    23203 non-null  int64
 33  mode_Split screen                                     23203 non-null  int64
 34  genre_Adventure                                       23203 non-null  int64
 35  genre_Arcade                                          23203 non-null  int64
 36  genre_Card & Board Game                               23203 non-null  int64
 37  genre_Fighting                                        23203 non-null  int64
 38  genre_Hack and slash/Beat 'em up                      23203 non-null  int64
 39  genre_Indie                                           23203 non-null  int64
 40  genre_MOBA                                            23203 non-null  int64
 41  genre_Music                                           23203 non-null  int64
 42  genre_Pinball                                         23203 non-null  int64
 43  genre_Platform                                        23203 non-null  int64
 44  genre_Point-and-click                                 23203 non-null  int64
 45  genre_Puzzle                                          23203 non-null  int64
 46  genre_Quiz/Trivia                                     23203 non-null  int64
 47  genre_Racing                                          23203 non-null  int64
 48  genre_Real Time Strategy (RTS)                        23203 non-null  int64
 49  genre_Role-playing (RPG)                              23203 non-null  int64
 50  genre_Shooter                                         23203 non-null  int64
 51  genre_Simulator                                       23203 non-null  int64
 52  genre_Sport                                           23203 non-null  int64
 53  genre_Strategy                                        23203 non-null  int64
 54  genre_Tactical                                        23203 non-null  int64
 55  genre_Turn-based strategy (TBS)                       23203 non-null  int64
 56  genre_Visual Novel                                    23203 non-null  int64
 57  theme_4X (explore, expand, exploit, and exterminate)  23203 non-null  int64
 58  theme_Action                                          23203 non-null  int64
 59  theme_Business                                        23203 non-null  int64
 60  theme_Comedy                                          23203 non-null  int64
 61  theme_Drama                                           23203 non-null  int64
 62  theme_Educational                                     23203 non-null  int64
 63  theme_Erotic                                          23203 non-null  int64
 64  theme_Fantasy                                         23203 non-null  int64
 65  theme_Historical                                      23203 non-null  int64
 66  theme_Horror                                          23203 non-null  int64
 67  theme_Kids                                            23203 non-null  int64
 68  theme_Mystery                                         23203 non-null  int64
 69  theme_Non-fiction                                     23203 non-null  int64
 70  theme_Open world                                      23203 non-null  int64
 71  theme_Party                                           23203 non-null  int64
 72  theme_Romance                                         23203 non-null  int64
 73  theme_Sandbox                                         23203 non-null  int64
 74  theme_Science fiction                                 23203 non-null  int64
 75  theme_Stealth                                         23203 non-null  int64
 76  theme_Survival                                        23203 non-null  int64
 77  theme_Thriller                                        23203 non-null  int64
 78  theme_Warfare                                         23203 non-null  int64
 79  developer                                             23203 non-null  str
 80  time_without_side_quests                              525 non-null    float64
 81  avg_time                                              669 non-null    float64
 82  completely                                            568 non-null    float64
 83  number_of_missions                                    710 non-null    float64
 84  num_alt_names                                         15016 non-null  float64
 85  additional_info                                       1018 non-null   str
 86  description                                           3051 non-null   str
 87  price                                                 3154 non-null   float64
 88  currency                                              3154 non-null   str
 89  tags                                                  3154 non-null   str
 90  reviews_total_reviews                                 3154 non-null   float64
 91  reviews_rating_value                                  3154 non-null   float64
 92  year                                                  23182 non-null  float64
dtypes: float64(17), int64(64), object(4), str(8)
memory usage: 20.0+ MB

In [13]:
df_rating_by_year = df_with_year.groupby('year')['rating']
df_rating_by_year = df_rating_by_year.mean().reset_index()

In [14]:
df_rating_by_year

      year     rating
0   1952.0  31.793258
1   1958.0  62.227261
2   1962.0  68.138435
3   1968.0  39.775281
4   1971.0  49.776558
5   1972.0  78.862076
6   1973.0  54.053211
7   1974.0  58.426966
8   1975.0  60.804373
9   1976.0  65.222564
10  1977.0  53.710227
11  1978.0  50.050259
12  1979.0  58.521574
13  1980.0  62.795743
14  1981.0  61.372556
15  1982.0  63.613161
16  1983.0  65.632289
17  1984.0  64.434933
18  1985.0  63.989088
19  1986.0  65.875555
20  1987.0  67.616661
21  1988.0  67.254730
22  1989.0  66.931700
23  1990.0  67.681653
24  1991.0  67.326161
25  1992.0  67.732080
26  1993.0  67.275760
27  1994.0  69.313051
28  1995.0  69.563345
29  1996.0  72.257479
30  1997.0  72.399484
31  1998.0  71.097208
32  1999.0  72.691934
33  2000.0  71.292352
34  2001.0  71.194715
35  2002.0  68.530332
36  2003.0  68.019470
37  2004.0  70.797833
38  2005.0  69.232975
39  2006.0  69.143654
40  2007.0  68.258949
41  2008.0  69.206629
42  2009.0  69.490563
43  2010.0  70.432279
44  2011.0  70.037248
45  2012.0  69.708274
46  2013.0  68.567871
47  2014.0  66.994727
48  2015.0  67.552567
49  2016.0  67.418335
50  2017.0  68.385035
51  2018.0  68.388345
52  2019.0  68.702532
53  2020.0  70.570868
54  2021.0  71.430628
55  2022.0  72.621475
56  2023.0  72.509156
57  2024.0  71.247334
58  2025.0  74.184652
59  2026.0  74.614468

In [15]:
pltexp.line(df_rating_by_year, x='year', y='rating', title='Средний рейтинг по годам', markers=True)

## График 3: Зависимость рейтинга игр от продуктивности компании (с частоты выхода игр)

Посмотрим, насколько сильно продуктивность студии влияет на рейтинг выпущенных ими игр. Это позволит сделать ряд допущений и выводов о том, какую стратегию компаниям лучше выбирать - выпускать как можно больше игры или бить редко, но метко

In [16]:
df_developers_by_rating = df_with_year.groupby('developer')
df_developers_by_rating = df_developers_by_rating.agg(mean_rating=('rating','mean'), count=("rating","count"), year_min=("year","min"), year_max=("year","max")).reset_index()

In [17]:
df_developers_by_rating

                        developer  mean_rating  count  year_min  year_max
0                                    65.688572   2041    1968.0    2025.0
1      (Archive) Capcom Co., LTD.    76.642036      2    2015.0    2024.0
2                              ,     74.000000      1    1990.0    1990.0
3                  .GEARS Studios    47.806087      1    2013.0    2013.0
4                    .theprodukkt    31.091217      1    2009.0    2009.0
...                           ...          ...    ...       ...       ...
10065                       墨鱼玩游戏    68.312716      1    2018.0    2018.0
10066                       拾英工作室    75.416027      1    2019.0    2019.0
10067                        旋風野郎    76.404494      1    2019.0    2019.0
10068                     蒸汽满满工作室    70.102925      1    2024.0    2024.0
10069                     高考恋爱委员会    80.000000      1    2015.0    2015.0

[10070 rows x 5 columns]

In [18]:
df_developers_by_rating = df_developers_by_rating[df_developers_by_rating["count"] > 1]

In [19]:
df_developers_by_rating = df_developers_by_rating[df_developers_by_rating["count"] < 100]

In [20]:
df_developers_by_rating = df_developers_by_rating.sort_values("count").reset_index()

In [21]:
df_developers_by_rating

      index         developer  mean_rating  count  year_min  year_max
0        30  1C: Maddox Games    71.680420      2    2006.0    2011.0
1       157               A44    72.194169      2    2018.0    2024.0
2       169  AHEARTFULOFGAMES    71.509192      2    2016.0    2024.0
3     10019      thecatamites    72.707787      2    2010.0    2016.0
4      9950    nStigate Games    62.097789      2    2009.0    2012.0
...     ...               ...          ...    ...       ...       ...
2826   2480         EA Canada    72.391690     67    1994.0    2018.0
2827   5566             Namco    69.970841     68    1980.0    2007.0
2828   8588    Telltale Games    75.764207     86    2005.0    2019.0
2829   9108  Ubisoft Montreal    70.916923     87    1999.0    2022.0
2830   5114             Maxis    65.407901     92    1991.0    2022.0

[2831 rows x 6 columns]

In [22]:
box_min_year = [elem for elem in df_developers_by_rating["year_min"]]
box_max_year = [elem for elem in df_developers_by_rating["year_max"]]
box_count = [elem for elem in df_developers_by_rating["count"]]

In [23]:
box_mean_gap_time = []

In [24]:
box_mean_gap_time

[]

In [25]:
for i in range (0, len(box_min_year)):
    box_mean_gap_time.append((box_max_year[i] - box_min_year[i]) / box_count[i])

In [26]:
box_mean_gap_time = pd.DataFrame(box_mean_gap_time, columns=['gap_year'])

In [27]:
box_mean_gap_time

      gap_year
0     2.500000
1     3.000000
2     4.000000
3     3.000000
4     1.500000
...        ...
2826  0.358209
2827  0.397059
2828  0.162791
2829  0.264368
2830  0.336957

[2831 rows x 1 columns]

In [28]:
df_developers_by_rating_with_mean_gap_time = pd.merge(df_developers_by_rating, box_mean_gap_time, left_index=True, right_index=True, how='inner')

In [29]:
df_developers_by_rating_with_mean_gap_time

,index,developer,mean_rating,count,year_min,year_max,gap_year
0,30,1C: Maddox Games,71.680420,2,2006.0,2011.0,2.500000
1,157,A44,72.194169,2,2018.0,2024.0,3.000000
2,169,AHEARTFULOFGAMES,71.509192,2,2016.0,2024.0,4.000000
3,10019,thecatamites,72.707787,2,2010.0,2016.0,3.000000
4,9950,nStigate Games,62.097789,2,2009.0,2012.0,1.500000
...,...,...,...,...,...,...,...
2826,2480,EA Canada,72.391690,67,1994.0,2018.0,0.358209
2827,5566,Namco,69.970841,68,1980.0,2007.0,0.397059
2828,8588,Telltale Games,75.764207,86,2005.0,2019.0,0.162791
2829,9108,Ubisoft Montreal,70.916923,87,1999.0,2022.0,0.264368
2830,5114,Maxis,65.407901,92,1991.0,2022.0,0.336957

In [30]:
df_developers_by_rating_with_mean_gap_time = df_developers_by_rating_with_mean_gap_time[df_developers_by_rating_with_mean_gap_time["gap_year"] < 3]

In [31]:
fig = pltexp.scatter(df_developers_by_rating_with_mean_gap_time, x='count', y='mean_rating', color='gap_year', opacity=0.6, size='count', title='Зависимость рейтинга игр от продуктивности компании (с частоты выхода игр)',)
fig.show()

## График 4: Зависимость количества доступных платформ и рейтинга игр

На этапе выбора стратегии разработки игр очень часто в первую очередь встает вопрос - а как лучше, разработать игру под как можно большее количество платформ или остановиться на одной/нескольких и не распылятся? Для этого мы выделили отдельную сущность "available_platforms", которая и позволяет посмотреть количество доступных платформ для определенёной игры. Построим график.

In [32]:
pltexp.box(df_with_year, x='available_platforms', y='rating', title='Зависимость количества доступных платформ и рейтинга игр')

## График 5: Средний рейтинг по жанрам

Для того, чтобы выбрать жанр, помимо тренда, который мы анализировали выше, нам также необходимо понимать средний рейтинг в каждом жанре. Для этого построим соответствующий график

In [33]:
box_by_years = []

In [34]:
box_genre = []

for elems in df_with_year.columns:
    if "genre" in elems:
        box_genre.append(elems)

In [35]:
box_by_years = []

for elems in box_genre:
    genre = elems.replace('genre_', '')
    ratings = df_with_year.loc[df[elems] == 1, 'rating']
    box_by_years.append({'genre': genre, 'mean_rating': ratings.mean(), 'count': len(ratings)})

In [36]:
graph_rating_genre = pd.DataFrame(box_by_years)
graph_rating_genre = graph_rating_genre.sort_values('mean_rating')
pltexp.bar(graph_rating_genre, x='mean_rating', y='genre', title='Средний рейтинг по жанрам', hover_data=['count'])

##  График 6: Зависимость длины игры и её рейтинга

На начальном этапе разработки игры также важно понимать, какой примерно длины мы будем разрабатывать игру. Делать её более длинной или всё же короткой. Для того, чтобы сделать необходимые выводы, посмотрим, как же влияет длина игры на её рейтинг. Для этого построим соответствующий график

In [59]:
df_time_grop = df_with_year.dropna(subset=['avg_time'])

In [60]:
df_time_grop = df_with_year[df_with_year['avg_time'] <= 400] # убираю выбросы, которые дольше чем 400 часов

In [62]:

pltexp.scatter(df_time_grop, x='avg_time', y='rating', title='Зависимость длины игры и её рейтинга', )